MD004: false # Unordered list style
MD007:
  indent: 2 # Unordered list indentation
MD012: false # Multiple consecutive blank lines
MD013:
  line_length: 5000 # Line length
MD024: false # Multiple headers with the same content
MD026:
  punctuation: '.,;:!。，；:' # List of not allowed
MD029: false # Ordered list item prefix
MD033: false # Allow inline HTML
MD034: false # Bare URL used
MD036: false # Emphasis used instead of a heading
MD038: false # Spaces inside emphasis markers
MD049: false # Emphasis style should be consistent
MD053: false # Super Linter broke this in v4.9.5
MD051: false # Allow broken link fragments
MD055: false # Table pipe style
MD056: false # Table column count
MD059: false # Allow non-descriptive link text
MD060: false # Table pipe does not align with heading for styled
